# Generated by Django 5.2.13 on 2026-07-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_chorale_currency'),
        ('membres', '0003_membre_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True = suppression logique, les données sont conservées.', verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('piece_jointe', models.FileField(blank=True, help_text='Document lié (lettre, affiche…). Optionnel.', null=True, upload_to='annonces/%Y/%m/', verbose_name='Pièce jointe')),
                ('epinglee', models.BooleanField(default=False, help_text='Une annonce épinglée remonte en tête du fil.', verbose_name='Épinglée')),
                ('date_expiration', models.DateField(blank=True, help_text="Après cette date, l'annonce disparaît du fil actif. Vide = permanente.", null=True, verbose_name="Date d'expiration")),
                ('auteur', models.ForeignKey(help_text="Membre (bureau ou maître de chœur) ayant publié l'annonce.", on_delete=django.db.models.deletion.PROTECT, related_name='annonces_publiees', to='membres.membre', verbose_name='Auteur')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-epinglee', '-created_at'],
            },
        ),
    ]
