# Generated by Django 5.2.13 on 2026-04-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom de la chorale')),
                ('prefix', models.CharField(help_text="Préfixe pour les matricules membres. Ex: 'LVO' → LVO-0042", max_length=5, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='chorales/logos/', verbose_name='Logo')),
                ('date_creation', models.DateField(help_text='Date de création/fondation de la chorale', verbose_name='Date de fondation')),
                ('devise', models.CharField(blank=True, max_length=200, verbose_name='Devise / Motto')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=25)),
                ('adresse', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour suspendre une chorale sans supprimer ses données.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Chorale',
                'verbose_name_plural': 'Chorales',
                'ordering': ['nom'],
            },
        ),
    ]
