# Generated by Django 5.2.13 on 2026-07-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorale',
            name='currency',
            field=models.CharField(choices=[('XOF', 'Franc CFA — BCEAO (XOF)'), ('XAF', 'Franc CFA — BEAC (XAF)'), ('EUR', 'Euro (€)'), ('USD', 'Dollar US ($)'), ('MAD', 'Dirham marocain (MAD)'), ('GHS', 'Cedi ghanéen (GHS)'), ('NGN', 'Naira nigérian (NGN)')], default='XOF', help_text='Devise utilisée pour toute la comptabilité de la chorale (défaut : Franc CFA XOF).', max_length=3, verbose_name='Monnaie de gestion'),
        ),
    ]
