# Generated by Django 5.2.13 on 2026-07-24 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chorale_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeChorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom_chorale', models.CharField(max_length=200, verbose_name='Nom de la chorale souhaité')),
                ('prefix_souhaite', models.CharField(blank=True, help_text="Suggestion du demandeur — l'opérateur confirme ou modifie le préfixe final.", max_length=5, verbose_name='Préfixe souhaité')),
                ('ville_pays', models.CharField(blank=True, max_length=200, verbose_name='Ville / Pays')),
                ('contact_nom', models.CharField(max_length=200, verbose_name='Nom du contact')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email du contact')),
                ('contact_telephone', models.CharField(blank=True, max_length=25)),
                ('message', models.TextField(blank=True, verbose_name='Message / motivation')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text="Capturée pour l'audit anti-abus, jamais exposée publiquement.", null=True, verbose_name='Adresse IP')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('prefix_attribue', models.CharField(blank=True, help_text="À renseigner par l'opérateur avant d'approuver — devient le préfixe réel de la chorale.", max_length=5, verbose_name='Préfixe attribué')),
                ('devise', models.CharField(choices=[('XOF', 'Franc CFA — BCEAO (XOF)'), ('XAF', 'Franc CFA — BEAC (XAF)'), ('EUR', 'Euro (€)'), ('USD', 'Dollar US ($)'), ('MAD', 'Dirham marocain (MAD)'), ('GHS', 'Cedi ghanéen (GHS)'), ('NGN', 'Naira nigérian (NGN)')], default='XOF', max_length=3, verbose_name='Devise attribuée')),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes (non visibles du demandeur)')),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('chorale_creee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='core.chorale', verbose_name='Chorale créée')),
            ],
            options={
                'verbose_name': "Demande d'adhésion chorale",
                'verbose_name_plural': "Demandes d'adhésion chorale",
                'ordering': ['-created_at'],
            },
        ),
    ]
