# Generated by Django 5.2.13 on 2026-04-14 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(max_length=60)),
                ('categorie', models.CharField(choices=[('soprano', 'Soprano'), ('mezzo', 'Mezzo-soprano'), ('alto', 'Alto'), ('tenor', 'Ténor'), ('baryton', 'Baryton'), ('basse', 'Basse'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie vocale')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans les listes (0 = premier)")),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
            ],
            options={
                'verbose_name': 'Pupitre',
                'verbose_name_plural': 'Pupitres',
                'ordering': ['ordre', 'nom'],
                'unique_together': {('chorale', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type_poste', models.CharField(choices=[('bureau', 'Bureau (élu)'), ('direction', 'Direction musicale'), ('technique', 'Technique / Organisation'), ('autre', 'Autre')], max_length=20, verbose_name='Type de poste')),
                ('unique_actif', models.BooleanField(default=True, help_text='Si True, un seul titulaire actif à la fois. Mettre False pour les postes de suppléant.')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
                ('groupes', models.ManyToManyField(blank=True, help_text="Groupes Django accordés automatiquement lors d'un mandat actif sur ce poste.", related_name='postes', to='auth.group')),
                ('pupitre_concerne', models.ForeignKey(blank=True, help_text='À renseigner uniquement pour un poste de chef de pupitre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes_chef', to='membres.pupitre')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['type_poste', 'nom'],
                'unique_together': {('chorale', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True = suppression logique, les données sont conservées.', verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('numero_membre', models.CharField(help_text='Identifiant lisible auto-généré. Ex : LVO-0042', max_length=20, unique=True, verbose_name='Numéro de membre')),
                ('date_adhesion', models.DateField(verbose_name="Date d'adhésion")),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('honoraire', 'Honoraire'), ('stagiaire', 'Stagiaire')], default='actif', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=25)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres/photos/')),
                ('notes', models.TextField(blank=True, help_text='Notes internes — visibles Bureau et Admin uniquement.')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membre', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('pupitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='membres.pupitre')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Laisser vide si le mandat est toujours en cours.', null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandats', to='membres.membre')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandats', to='membres.poste')),
            ],
            options={
                'verbose_name': 'Mandat',
                'verbose_name_plural': 'Mandats',
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('membre', 'poste'), name='unique_mandat_actif_par_membre_poste')],
            },
        ),
    ]
