# Generated by Django 5.2.13 on 2026-07-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_data_bootstrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='sexe',
            field=models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], help_text='Utilisé notamment pour les tarifs de cotisation par genre.', max_length=10, verbose_name='Sexe'),
        ),
    ]
