# Generated by Django 5.2.13 on 2026-07-24 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_demandechorale'),
        ('membres', '0003_membre_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationChorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('note', models.CharField(blank=True, help_text='Usage interne, ex. « Recrutement pupitre hommes — Pâques 2026 ».', max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('expire_le', models.DateField(blank=True, help_text="Vide = pas d'expiration.", null=True, verbose_name='Expire le')),
                ('max_utilisations', models.PositiveIntegerField(blank=True, help_text='Vide = illimité. Mettre 1 pour une invitation nominative à usage unique.', null=True, verbose_name='Utilisations maximum')),
                ('nombre_utilisations', models.PositiveIntegerField(default=0, verbose_name='Utilisations')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_creees', to='membres.membre', verbose_name='Créé par')),
                ('pupitre_suggere', models.ForeignKey(blank=True, help_text='Pré-affecte le pupitre du membre qui rejoint via ce code (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='membres.pupitre', verbose_name='Pupitre suggéré')),
            ],
            options={
                'verbose_name': 'Invitation chorale',
                'verbose_name_plural': 'Invitations chorale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='invitation_utilisee',
            field=models.ForeignKey(blank=True, help_text="Code d'invitation ayant servi à l'inscription, le cas échéant (traçabilité).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_inscrits', to='membres.invitationchorale', verbose_name='Invitation utilisée'),
        ),
    ]
