# Generated by Django 5.2.13 on 2026-04-14 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date', models.DateField(verbose_name='Date de la répétition')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('resume', models.TextField(blank=True, help_text='Ce qui a été travaillé, observations, décisions prises…', verbose_name='Résumé de la séance')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
                ('dirigee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repetitions_dirigees', to='membres.membre', verbose_name='Dirigée par')),
            ],
            options={
                'verbose_name': 'Répétition',
                'verbose_name_plural': 'Répétitions',
                'ordering': ['-date', '-heure_debut'],
                'unique_together': {('chorale', 'date', 'heure_debut')},
            },
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_debut', models.DateField(verbose_name="Début de l'absence")),
                ('date_fin', models.DateField(verbose_name="Fin de l'absence")),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_permission', to='membres.membre', verbose_name='Demandeur')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_traitees', to='membres.membre', verbose_name='Traitée par')),
                ('repetition', models.ForeignKey(blank=True, help_text='Répétition spécifique concernée (optionnel si plage de dates)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_permission', to='presences.repetition')),
            ],
            options={
                'verbose_name': 'Demande de permission',
                'verbose_name_plural': 'Demandes de permission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('permission', 'En permission'), ('retard', 'En retard')], max_length=20, verbose_name='Statut de présence')),
                ('motif', models.TextField(blank=True, help_text="Motif de l'absence ou du retard")),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='membres.membre')),
                ('repetition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='presences.repetition')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['membre__user__last_name'],
                'unique_together': {('repetition', 'membre')},
            },
        ),
    ]
