# Generated by Django 5.2.13 on 2026-04-14 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('membres', '0001_initial'),
        ('presences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True = suppression logique, les données sont conservées.', verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du chant')),
                ('compositeur', models.CharField(blank=True, max_length=200, verbose_name='Compositeur / Auteur')),
                ('style', models.CharField(choices=[('classique', 'Classique'), ('moderne', 'Moderne'), ('traditionnel', 'Traditionnel'), ('gospel', 'Gospel'), ('liturgique', 'Liturgique'), ('autre', 'Autre')], max_length=20, verbose_name='Genre / Style')),
                ('tonalite', models.CharField(blank=True, help_text='Ex: Do majeur, Si bémol mineur', max_length=10, verbose_name='Tonalité')),
                ('tempo', models.CharField(blank=True, help_text='Ex: Allegro, 120 BPM, Lent', max_length=50)),
                ('notes', models.TextField(blank=True, help_text="Notes sur le chant, consignes d'interprétation, etc.")),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
            ],
            options={
                'verbose_name': 'Chant',
                'verbose_name_plural': 'Chants',
                'ordering': ['titre'],
                'unique_together': {('chorale', 'titre', 'compositeur')},
            },
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('titre', models.CharField(help_text="Ex: 'Partition Soprano', 'Score complet'", max_length=200, verbose_name='Titre du fichier')),
                ('fichier', models.FileField(upload_to='partitions/%Y/%m/', verbose_name='Fichier (PDF, image…)')),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='musique.chant')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
                ('type_voix', models.ForeignKey(blank=True, help_text='Laisser vide si la partition est pour toutes les voix.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partitions', to='membres.pupitre', verbose_name='Pupitre concerné')),
            ],
            options={
                'verbose_name': 'Partition',
                'verbose_name_plural': 'Partitions',
                'ordering': ['chant__titre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='SeanceChant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('statut', models.CharField(choices=[('introduit', 'Introduit'), ('en_travail', 'En travail'), ('maitrise', 'Maîtrisé')], default='introduit', max_length=20, verbose_name="Statut d'apprentissage")),
                ('notes', models.TextField(blank=True, help_text='Observations sur la séance (difficultés, progrès…)')),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='musique.chant')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
                ('repetition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chants_travailles', to='presences.repetition', verbose_name='Répétition')),
            ],
            options={
                'verbose_name': 'Chant travaillé en séance',
                'verbose_name_plural': 'Chants travaillés en séance',
                'ordering': ['-repetition__date'],
                'unique_together': {('repetition', 'chant')},
            },
        ),
    ]
