# Generated by Django 5.2.13 on 2026-07-23 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chorale_currency'),
        ('musique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(max_length=80, verbose_name='Thème')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
            ],
            options={
                'verbose_name': 'Thème',
                'verbose_name_plural': 'Thèmes',
                'ordering': ['nom'],
                'unique_together': {('chorale', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='chant',
            name='themes',
            field=models.ManyToManyField(blank=True, help_text='Thématiques du chant (tags), pour regrouper et filtrer le répertoire.', related_name='chants', to='musique.theme', verbose_name='Thèmes'),
        ),
    ]
