# Generated by Django 5.2.13 on 2026-04-14 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True = suppression logique, les données sont conservées.', verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('date', models.DateField(verbose_name='Date du mouvement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('sens', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Sens')),
                ('motif', models.CharField(max_length=300, verbose_name='Motif / Libellé')),
                ('piece_jointe', models.FileField(blank=True, upload_to='finances/%Y/%m/', verbose_name='Pièce justificative')),
            ],
            options={
                'verbose_name': 'Mouvement financier',
                'verbose_name_plural': 'Mouvements financiers',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaiementCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('date_paiement', models.DateField(verbose_name='Date du paiement')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Paiement de cotisation',
                'verbose_name_plural': 'Paiements de cotisation',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='CampagneCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('description', models.TextField(blank=True)),
                ('type_campagne', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('annuelle', 'Annuelle'), ('ponctuelle', 'Ponctuelle'), ('evenementielle', 'Événementielle')], max_length=20, verbose_name='Type')),
                ('montant_unitaire', models.DecimalField(decimal_places=2, help_text='Montant attendu de chaque membre concerné', max_digits=10, verbose_name='Montant par membre')),
                ('date_debut', models.DateField(verbose_name='Début de la collecte')),
                ('date_fin', models.DateField(blank=True, help_text='Laisser vide si pas de deadline', null=True, verbose_name='Date limite')),
                ('is_obligatoire', models.BooleanField(default=True, help_text='Si True, génère automatiquement une cotisation pour chaque membre actif', verbose_name='Obligatoire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
            ],
            options={
                'verbose_name': 'Campagne de cotisation',
                'verbose_name_plural': 'Campagnes de cotisation',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CategorieMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Type')),
                ('description', models.TextField(blank=True)),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
            ],
            options={
                'verbose_name': 'Catégorie de mouvement',
                'verbose_name_plural': 'Catégories de mouvement',
                'ordering': ['type_mouvement', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True = suppression logique, les données sont conservées.', verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('montant_du', models.DecimalField(decimal_places=2, help_text='Peut différer du montant_unitaire (exonération partielle)', max_digits=10, verbose_name='Montant dû')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('partiel', 'Partiel'), ('paye', 'Payé'), ('exonere', 'Exonéré')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='finances.campagnecotisation', verbose_name='Campagne')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-campagne__date_debut'],
            },
        ),
    ]
