# Generated by Django 5.2.13 on 2026-04-14 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finances', '0001_initial'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='membres.membre'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='finances.categoriemouvement', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='chorale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_enregistres', to='membres.membre', verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='membre',
            field=models.ForeignKey(blank=True, help_text='Membre lié au mouvement (paiement cotisation, don nominatif…)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='membres.membre', verbose_name='Membre concerné'),
        ),
        migrations.AddField(
            model_name='paiementcotisation',
            name='cotisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finances.cotisation'),
        ),
        migrations.AddField(
            model_name='paiementcotisation',
            name='mouvement',
            field=models.OneToOneField(blank=True, help_text='Lien vers le mouvement dans le journal de caisse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement_cotisation', to='finances.mouvement', verbose_name='Mouvement correspondant'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriemouvement',
            unique_together={('chorale', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='cotisation',
            unique_together={('campagne', 'membre')},
        ),
    ]
