# Generated by Django 5.2.13 on 2026-07-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chorale_currency'),
        ('finances', '0002_initial'),
        ('membres', '0003_membre_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(max_length=100, verbose_name='Libellé du tarif')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('critere_sexe', models.CharField(blank=True, help_text="Si renseigné, ce tarif s'applique aux membres de ce sexe.", max_length=10, verbose_name='Critère sexe')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='finances.campagnecotisation')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
                ('critere_pupitre', models.ForeignKey(blank=True, help_text="Si renseigné, ce tarif s'applique aux membres de ce pupitre.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_cotisation', to='membres.pupitre', verbose_name='Critère pupitre')),
            ],
            options={
                'verbose_name': 'Tarif de cotisation',
                'verbose_name_plural': 'Tarifs de cotisation',
                'ordering': ['campagne', 'nom'],
            },
        ),
    ]
