# Generated by Django 5.2.13 on 2026-07-24 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_demandechorale'),
        ('membres', '0004_invitationchorale_membre_invitation_utilisee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('type_notification', models.CharField(choices=[('permission', "Demande d'absence"), ('mandat', 'Mandat / poste'), ('annonce', 'Annonce'), ('cotisation', 'Cotisation'), ('systeme', 'Système')], default='systeme', max_length=20, verbose_name='Type')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('lien', models.CharField(blank=True, help_text='Route frontend vers la ressource concernée. Ex : /presences/permissions', max_length=200)),
                ('lue', models.BooleanField(db_index=True, default=False, verbose_name='Lue')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.chorale', verbose_name='Chorale')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='membres.membre', verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
